### ISSUE TITLE
Vite v6

### ISSUE THREAD

**Issue by Victor-Salomon** [victor-lillo/react-vite-component-template#3]
Hey @victor-lillo, 

Thanks for the article and the open-source repo!

I'm not directly reporting an issue, but I'm curious why you chose Vite v5.x.x instead of v6, given that v6 is already out. It seems v6 introduces a different configuration (with a `tsconfig.app.json` some `"tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo"`, and I haven't found much documentation on setting up the build properly with v6. Have you experienced any issues with the last version?

The only way I can generate the types with `dts` from 'vite-plugin-dts' is by adding some params to the dts plugin: 
```
dts({
 tsconfigPath: 'tsconfig.app.json',
 rollupTypes: true,
}),
```

Thanks in advance for your feedback 🙏

**Comment by victor-lillo** [comment]
Hello @Victor-Salomon, and thanks for your question!

When I created the repo, Vite 6 hadn't been released yet, so I built it with Vite 5, that's the reason 😅

I haven’t had the time lately to look into Vite 6 and its new features and configurations due to my limited availability. I will do as soon as I can. By the way, if you're interested in contributing, a pull request would be very welcome!

**Comment by victor-lillo** [comment]
Well, finally, I could test Vite 6 (not so deep) and, following the [`vite-plugin-dts`](https://github.com/qmhc/vite-plugin-dts?tab=readme-ov-file#usage) documentation, simply adding `tsconfigPath: 'tsconfig.app.json'` worked for me.

```ts
    dts({
      exclude: ['**/*.stories.tsx', 'src/test', '**/*.test.tsx'],
      tsconfigPath: 'tsconfig.app.json',
    }),
```

![Image](https://github.com/user-attachments/assets/729a503a-5012-49aa-a156-e93c3253780e)

I didn't use `rollupTypes: true`, it's only for merging all types into a single file.

I've created a [branch for the Vite 6 update](https://github.com/victor-lillo/react-vite-component-template/tree/feature/update-to-vite-6). When I have the time, I plan to test it more properly, update the article, and merge it into the main repository. 

Feel free to try it out and let me know how it goes!

**Comment by Victor-Salomon** [comment]
@victor-lillo thanks for giving it a try that quick. I'll look into your Branch and see your implementation.
I'll let you know the outcome of this.

**Comment by victor-lillo** [comment]
Hello @Victor-Salomon ,

I’m closing this issue as I have just merged PR #5. Everything is working as expected with Vite 6 and React 19.

Feel free to reopen the issue if you need anything else.

Thanks!

**Comment by Victor-Salomon** [comment]
@victor-lillo thanks a lot. 
I’m making progress with my project, but I’m still having some trouble creating a stable build that can actually be used.
My setup is quite similar, but it includes Tailwind and aliases.
It was working fine when my components were still basic (just mockups), but things broke after I implemented the actual widget I’m working on.
Anyway, thanks a lot 👋
